let easyQuestions = [
    [ 'easyQuestion1',                      //问题
        'A',                                //选项
        'B',
        'C',
        'D',
        'A' ],                              //答案
    [ 'easyQuestion2',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'easyQuestion3',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'easyQuestion4',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'easyQuestion5',
        'A',
        'B',
        'C',
        'D',
        'A' ]
    // [ 'easyQuestion6',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion7',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion8',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion9',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion10',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion11',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion12',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion13',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion14',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion15',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion16',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion17',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion18',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion19',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion20',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion21',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion22',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion23',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion24',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion25',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion26',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion27',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion28',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion29',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion30',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion31',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion32',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion33',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion34',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion35',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion36',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion37',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion38',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion39',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion40',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion41',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion42',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion43',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion44',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion45',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion46',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion47',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion48',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion49',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'easyQuestion50',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
];
