let hardQuestions = [
    [ 'hardQuestion1',                      //问题
        'A',                                //选项
        'B',
        'C',
        'D',
        'A' ],                              //答案
    [ 'hardQuestion2',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'hardQuestion3',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'hardQuestion4',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'hardQuestion5',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    // [ 'hardQuestion6',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion7',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion8',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion9',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion10',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion11',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion12',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion13',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion14',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion15',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion16',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion17',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion18',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion19',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion20',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion21',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion22',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion23',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion24',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion25',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion26',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion27',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion28',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion29',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion30',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion31',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion32',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion33',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion34',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion35',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion36',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion37',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion38',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion39',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion40',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion41',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion42',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion43',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion44',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion45',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion46',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion47',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion48',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion49',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'hardQuestion50',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
];
