let simpleQuestions = [
    [ 'simpleQuestion1',     //问题
        'A',                                //选项
        'B',
        'C',
        'D',
        'A' ],                              //答案
    [ 'simpleQuestion2',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'simpleQuestion3',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'simpleQuestion4',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    [ 'simpleQuestion5',
        'A',
        'B',
        'C',
        'D',
        'A' ],
    // [ 'simpleQuestion6',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion7',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion8',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion9',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion10',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion11',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion12',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion13',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion14',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion15',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion16',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion17',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion18',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion19',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion20',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion21',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion22',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion23',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion24',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion25',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion26',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion27',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion28',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion29',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion30',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion31',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion32',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion33',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion34',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion35',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion36',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion37',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion38',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion39',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion40',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion41',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion42',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion43',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion44',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion45',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion46',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion47',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion48',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion49',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
    // [ 'simpleQuestion50',
    //     'A',
    //     'B',
    //     'C',
    //     'D',
    //     'A' ],
];
